---
- name: Install Docker and Run SonarQube Container
  hosts: tag_sonarqube_server
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      
    - name: Install OpenJDK
      apt:
        name: openjdk-11-jdk   # Change this to the appropriate OpenJDK version you want
        state: present
        
    - name: Install required packages for Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker-ce
        state: latest

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add your user to the Docker group
      user:
        name: ubuntu  # Replace with your username
        groups: docker
        append: yes

    - name: Docker login to Docker Hub
      docker_login:
        username: prajwal1691
        password: Prajwal@91

    - name: Debugging
      debug:
        msg: "Image name: sonarqube, Tag: latest"

    - name: Pull SonarQube Docker image
      docker_image:
        name: sonarqube
        tag: latest
        source: pull

    - name: Create network for SonarQube container
      docker_network:
        name: sonarqube_network

    - name: Run SonarQube container
      docker_container:
        name: sonarqube
        image: sonarqube
        ports:
          - "9000:9000"
      register: sonarqube_container

    - name: Display Docker containers' information
      command: docker ps
